server:
  port: 7000

spring:
  datasource:
   # url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2b8
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource

  application:
    name: SCW-USER

  redis:
    password: 123456
    host: 192.168.19.133
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    path: D:\\Java\\idea\\TypeRoom\\log
  level:
    com:
      offcn: debug
sms:
  host: http://dingxin.market.alicloudapi.com
  path: /dx/sendSms
  method: POST
  appCode: APPCODE c5e745d2b72b44439bbda51e105eab6e

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml